Feature #56 모달컴포넌트 위치 변경과 사진내려받기 기능 관련
miind-palace/mind-palace-FE pull request #63
Opened 2023-07-17 18:13 UTC by j2h30728

## 관련 문서

Closes #56

## 변경사항:

1. 사진 내려방기 기능 중, `object-fit: 'contain'` 속성 적용 완료
2. 모달컴포넌트 위치 변경
3. youtube helper 함수 변경

### 사진 내려방기 기능 에러 
**에러 해결내용**
 현재, 사진 내려받기 기능은 html2canvas 라이브러리를 사용하고있습니다. 
폴라로이드 디자인내에 이미지를 알맞게 스타일링을 하기위해서 현재 CSS 속성 중, `object-fit: 'contain'`을 적용하고 있습니다.
하지만, html2canvas는 해당 속성을 지원하지않습니다.  [링크로 확인](https://html2canvas.hertzen.com/features)
<img width="416" alt="image" src="https://github.com/miind-palace/mind-palace-FE/assets/60846068/8c73ce3b-5144-45f4-942b-933152ff5b55">

https://github.com/miind-palace/mind-palace-FE/pull/30  이전, 사진내려받기 기능 에러에 대한 첫번째 조치에 대한 풀리퀘입니다.
이 풀리퀘에서 Img, Image 태그를 사용할 경우에, 필수적으로 `object-fit: 'contain'` 을 적용해야하기 떄문에 div 태그의 background-url을 사용하여 우회하는 작업으로 해결하였습니다.

데이터베이스와 연결한후, 여러 잠재적인 에러들과 만나게 되면서 div 태그에 이미지가 로드되지 않고 빈 이미지만 다운로드되는 에러가 발생하게 됩니다.
 해당 라이브러리는 당시에는 Next.js 에서 제공하고있는 Image 컴포넌트의 `onLoad` 를 사용하여, 이미지가 로드가 완료 될때에만 이미지 다운로드를 진행할 수 있게 하였습니다.

하지만, Next.js에서 제공하는 Image 컴포넌트를 사용할 경우에는 html2canvas가 제공하지않는 `object-fit: 'contain`'이 필요하기 때문에 patch-package를 사용하여 라이브러리 코드를 수정 하였습니다.
=> [해당 라이브러리의 깃이슈 링크](https://github.com/niklasvh/html2canvas/issues/2541)

현재, package.json 에 npm i 할 경우에 바로 patch를 하게끔 설정하였으나, next 빌드 폴더를 먼저 삭제하신 후, npm i 을 부탁드립니다.

**남아 있는 문제점**
사진 내려받기 기능을 진행할 경우, `object-fit: 'contain'` 은 적용이 되는 것을 확인 할 수있습니다.

하지만, 크롭된 이미지가 다운되는 상황이 발생됩니다.
이는, 웹을 실행한후 일정 시간이 지나지 않은채 바로 사진 내려받기 기능을 할 경우에 발생됩니다.
넥스트 이미지의 캐싱이 필요한 시간이 필요한건지, html2canvas가 처리되는 시각이 다른 것인 확인할 수가 없었습니다.

|일정시간이 지난후, 사진을 내려받을 경우(Next Image사용) | 접속하자마자 사진을 내려받을 경우(Next Image사용) |img, div태그 사용후, 사진 내려받기할 경우|
|-|-|-|
|![image](https://github.com/miind-palace/mind-palace-FE/assets/60846068/23305c76-9e5b-44f3-82bc-99285da5982a) | ![image](https://github.com/miind-palace/mind-palace-FE/assets/60846068/eedc40bd-7824-4554-9239-6d63dba54643) | ![image](https://github.com/miind-palace/mind-palace-FE/assets/60846068/9fb0ac4d-8bff-421c-b99e-0e33ecf65650)|

### 모달컴포넌트 위치 변경
모달은 페이지 기준으로 생성되는 컴포넌트 입니다.
Card 컴포넌트안으로 이동되었던 컴포넌트 위치를 memory-list 페이지로 이동시켰습니다.

### youtube helper 함수 변경
이전에 변경되어있던 youtube helper함수는 제가 작성한 의도와 목적과 달리 계속 수정되었습니다.
이전 풀리퀘에서 작성된 함수로 변경하였습니다. [커밋](https://github.com/miind-palace/mind-palace-FE/pull/30/commits/b6443aba7c049ed406a25295f990e1e870426261#diff-2e4f40bf1e8742fdbd88ede26fa48819593909f74efb92a79a2d0aceb7b61a0a)
- youtube 링크가 인자로 들어올 경우, videoId 만 반환함.
- 만약, youtube 링크가 아닐경우에는 undefined를 반환.
- 업로드 페이지에서는   사용자가 videoId를 가지고있지않는 유효하지않는 링크를 넣었을 경우와 사용자가 yotube링크를 넣지않는 경우를 모두 고려해 OR 연산자를 이용해 `videoId={makeYouTubeVideoId(youtubeUrl) || ''}` 빈 문자열을 데이터베이스로 보내주도록함. [변경된 업로드 페이지 코드](https://github.com/miind-palace/mind-palace-FE/commit/b6d148190adde7e0854172f642a349f897e4d070#diff-8b07930297ae3563afd6409d15a82287443e1094d578dce1c676f7e526f862e6R113)
- 현재, 데모버전의 데이터베이스에서는 videoId 가 아닌 youtube Url 도 들어가 있는 상황이기 때문에 재생되는 부분에서는` videoId={makeYouTubeVideoId(memory.videoId) || memory.videoId}`로 옵셔널 처리하도록 함 [Card 컴포넌트에서 변경된 코드](https://github.com/miind-palace/mind-palace-FE/commit/09d671fdf4507c8deca13df957abcf1882c255bc#diff-e22256f39ac14daca0b6c7400341c609995c98d4924c8c73d0a6b64d8d7006b0R20)

## 확인할 목록:

1. 모달의 사진내려받기 기능을 함께 테스트 부탁드립니다. 혹시, 어느 부분에서 문제가 잔재하고있는지 확인부탁드립니다.

> 테스트하실 경우, next 빌드 폴더를 먼저 삭제하신 후, npm i 을 부탁드립니다.

2. youtube video Id helper 함수를 수정하면서, 제가 담당하지 않는 Upload 페이지와 Card 컴포넌트의 코드가 수정되었습니다.

2023-07-20 13:18 UTC, Jooeun-K commented on pages/upload/index.tsx
> +          <YouTubePlayer videoId={makeYouTubeVideoId(youtubeUrl) || ''} isAutoPlay={true} />
이건 취향 문제라서 꼭 반영은 안해도 되는데, props에 이렇게 직접 defaultValue를 넣어주는 것 보다는 YouTubePlayer 컴포넌트 내부에서 props 받아오는 쪽에 직접 해당 값에 대한 defaultValue를 넣어주는게 더 깔끔하지 않을까요? 예를 들면 이런 느낌..

```suggestion
          <YouTubePlayer videoId={makeYouTubeVideoId(youtubeUrl)} isAutoPlay={true} />
```

```ts
// YouTubePlayerButton.tsx

// ...

interface YouTubePlayerProps {
  videoId?: string
  isAutoPlay: boolean
  isInMemoryList?: boolean
}
const YouTubePlayer: React.FC<YouTubePlayerProps> = ({ videoId = '', isAutoPlay, isInMemoryList }) => {

// more code ...

```

2023-07-20 13:19 UTC, Jooeun-K commented on components/Modal/MemoryDetail.tsx
>  const Date = styled.span`
요거요거 javascript의 Date 객체랑 이름이 겹칠 수 있어서 안좋은 이름이라고 생각합니당
`DateSpan`같은걸로 변경 어떨까요

```suggestion
const DateSpan = styled.span`
```

2023-07-20 13:20 UTC, Jooeun-K commented on components/Modal/MemoryDetail.tsx
> +import YouTubePlayer from '../button/YouTubePlayerButton'
컴포넌트 파일명은 YoutubePlayerButton인데 왜 import는 YouTubePlayer로 해왔나요??

2023-07-20 13:22 UTC, Jooeun-K commented on pages/memory-list/index.tsx
> +import { memo, useCallback, useEffect, useRef, useState } from 'react'
```suggestion
import { useCallback, useEffect, useRef, useState } from 'react'
```
memo는 import만 하고 사용은 안한 것 같아요!

2023-07-20 13:24 UTC, Jooeun-K commented on package.json
> +    "postinstall": "patch-package",
이 패키지도 진짜 왕신기..
[NPM Link](https://www.npmjs.com/package/postinstall)

2023-07-20 13:26 UTC, Jooeun-K commented on next.config.js
> +  },
보안상 domains보다는 remotePatterns 옵션을 사용하는게 좋다고 Next.js 공식 문서에서도 권장하고 있어서요! remotePatterns로 대체 가능한지 한번 확인해주시겠어요??

Ref 1 : [Next.js 공식 문서 image domains 항목](https://nextjs.org/docs/app/api-reference/components/image#domains)
Ref 2 : [Next.js 공식 문서 image remotePatterns 항목](https://nextjs.org/docs/app/api-reference/components/image#remotepatterns)

2023-07-20 13:28 UTC, Jooeun-K commented on pages/upload/index.tsx
> +import YouTubePlayer from '@/components/button/YouTubePlayerButton'
여기도 컴포넌트 파일명은 YoutubePlayerButton인데 import는 YouTubePlayer로 해오고 있네요. 이유가 있나요??

2023-07-20 14:13 UTC, j2h30728 commented on components/Modal/MemoryDetail.tsx
> +          />
`sizes="100vw"` 코드를 넣고 다운로드를 할경우에도 일정시간을 기다려야지만 정확한 사진이 다운로드가 되네요.😭..

시크릿모드, 파이어폭스로 켜봐도 다 아래 사진형태로 나옵니다.😭
![Uploading my_memory - 2023-07-20T230818.358.png…]()

2023-07-20 14:14 UTC, j2h30728 commented on components/Modal/MemoryDetail.tsx
> +          />
`sizes="100vw"` 코드를 넣고 다운로드를 할경우에도 일정시간을 기다려야지만 정확한 사진이 다운로드가 되네요.😭..

시크릿모드, 파이어폭스로 켜봐도 다 아래 사진형태로 나옵니다.😭
![my_memory - 2023-07-20T230818 358](https://github.com/miind-palace/mind-palace-FE/assets/60846068/eb40ccf7-6303-45d3-a855-8cfdc4b22bff)

2023-07-20 14:15 UTC, Jooeun-K commented on components/Modal/MemoryDetail.tsx
> +          />
😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 
좀 더 살펴보도록 하겠읍니다.. @j2h30728

2023-07-20 15:02 UTC, j2h30728 commented on components/Modal/MemoryDetail.tsx
>  const Date = styled.span`
감사합니다! 수정했어요!

2023-07-20 15:11 UTC, j2h30728 commented on next.config.js
> +  },
오! `remotePatterns` 부분은 오늘 처음 알았어요! 감사합니다. 더 강력한 보안을 위해서 `remotePatterns ` 로 수정했습니다!

2023-07-20 16:13 UTC, Jooeun-K commented on components/Modal/MemoryDetail.tsx
> +          />
[html-to-image](https://www.npmjs.com/package/html-to-image#toPng) 라이브러리로 교체해보는건 어떠신가요..? @j2h30728 

html2canvas가 html을 canvas로 전환하는 과정에서 뭔가 틀어지거나 딜레이가 생기는 것 같아서, canvas 전환 없이 바로 html -> img 전환시켜주는 라이브러리를 찾아봤습니다. 요놈으로 교체하면 해결될수도 있지 않을까..! 싶어요. 🤔
(일단 제가 해봤을때는 됐음..)

2023-07-20 16:19 UTC, Jooeun-K commented on components/Modal/MemoryDetail.tsx
>    const downloadImageId = 'download-image'
그리고 뒤늦게 발견했는데 이 상수....!!!
컴포넌트 내부에 있으면 상태 변경될떄마다 컴포넌트랑 같이 리렌더링 될 것 같아요.
useRef로 리렌더링 안일어나도록 감싸주거나, 컴포넌트 외부로 빼주는게 좋을 것 같습니다

```ts
const downloadImageId = useRef('download-image')
```
혹은
```ts

// ...

const downloadImageId = 'download-image'

const MemoryDetail = ({
  backgroundImage,
  videoId,
  text,
  createdAt,
  onClickCloseModal,
  onClickRemoveMemory,
}: MemoryProps) => {
  const [isImageLoaded, setIsImageLoaded] = useState(false)
  
  // more code ...
```

2023-08-02 08:52 UTC, j2h30728 commented
## 변경사항:

1. html2canvas 에서 html-to-image로 라이브러리 변경
2. 사진 다운로드시, 로더 표출

### 사진 내려 받기 기능에서의 라이브러리 변경

사진 내려받기 기능을 진행할 경우에 크롭된 이미지가 다운되는 상황과 이유를 찾을 수 없었습니다.
잠재되는 해당 에러 발생을 방지하고자 html2canvas 에서 html-to-image로 라이브러리를 변경했습니다. 

### 사진 다운로드시 로더 표출
html-to-image로 라이브러리를 변경하고나서 다운로드 딜레이 시간이 생겼습니다.
이전과 같이 다운로드 버튼을 누르고나서 사용자에게 알려주지 않느다면, 사용자는 다운로드가 진행중인지 알지 못한채로 다운 버튼을 연속적으로 누르거나 다른 이상행동을 할 가능성이 있습니다.
이에 허니비와 협의하여 전체 화면 오버레이를 적용한 로더를 표출합니다.


## 확인할 목록:

- 사진 내려받기 중에 표출되는 로더의 색상이 하단에 존재하는 추억의 이미지와 겹쳐질경우를 대비해서 로더 색상을 사용처에서 사용할수 있게 열어주는 방법도 좋을 것같습니다.
- 현재 오버레이의 색상은 `background-color: rgba(0, 0, 0, 0.2);` 이러합니다. 이부분도 함께 고려부탁드립니다.

 |이미지색상이 밝을 경우|이미지색상이 어두울 경우|
|-|-|
|![image](https://github.com/miind-palace/mind-palace-FE/assets/60846068/8f365561-83bc-4573-8fa4-e2c9adc7fa70)|![image](https://github.com/miind-palace/mind-palace-FE/assets/60846068/58589a76-af0c-44cb-a6e3-29aabfc5a20c)|

2023-08-05 09:39 UTC, Jooeun-K requested changes
크.. 고생하셨습니다 다운로드 기능 정상적으로 작동하는 것 확인했어요 👏👏👏👏👏👏

그런데 추가로 발견한 이슈가 하나 더 있어서 리뷰 답니다
(ㅠㅠ 지난번에는, 그리고 스프린트 기간에는 시간이 빠듯해 미처 체크하지 못했던 것 같아요)
<img width="1512" alt="스크린샷 2023-08-05 오후 6 17 31" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/9e301962-f0cf-4495-907f-e1964899ec3c">

실제 모바일 화면에서 보면 이렇게 화면이 깨져서 보이네요..!
기능상 이슈는 없고, 스타일 부분만 체크 한 번 부탁드립니다~

2023-08-05 09:39 UTC, Jooeun-K commented on components/memory-list/MemoryDetail.tsx
> -  min-width: 400px;
여기서 최소값을 한정하고 있어서, 490x663 미만의 규격을 가진 화면에서는 모달이 정상적으로 노출되지 않는 것 같아요. 확인 후 수정 부탁드립니다~
-> 절대값이 아니라 상대값으로 변경해야 할 것 같고
-> 이 부분을 상대값으로 수정하면 아마 하위 컴포넌트 규격도 맞춰서 수정해야 할 거예요

2023-08-08 15:02 UTC, j2h30728 commented on components/memory-list/MemoryDetail.tsx
> -  min-width: 400px;
감사해요!! 곰곰이 말해줘서 바로 수정할 수 있었어요!

2023-08-09 14:13 UTC, Jooeun-K requested changes
사용성에 문제가 있는 UI 이슈가 있어서 코멘트 남겼습니다. 확인 부탁드려요!

2023-08-09 14:13 UTC, Jooeun-K commented on components/memory-list/MemoryDetail.tsx
>    min-height: 663px;
담.. 자꾸 request changes를 걸어서 미안해요. 😢 
하지만 이건 명백하게 유저 사용성에 문제가 있는 부분이라 짚고 넘어가는 점 양해 부탁드립니다 (ㅠㅠ)

viewport height가 663px 이하인 기기에서 height가 정상적으로 노출되는지도 체크가 필요해보입니다~
이런식으로 깨져보이네요! (아이폰 se, 갤럭시 S8+ 기준)
|아이폰se|갤럭시S8+|
|---|---|
|<img width="457" alt="스크린샷 2023-08-09 오후 10 57 55" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/5e4d3232-1435-4d82-a382-c8c59c66cbf4">|<img width="457" alt="스크린샷 2023-08-09 오후 10 57 55" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/5fdd15ce-ac1a-4485-8c64-8d0c87f23399">|

정상적으로 노출되는 기기에서는 다음과 같이 보입니다~

|IOS|안드로이드|
|---|---|
|<img width="456" alt="스크린샷 2023-08-09 오후 10 58 20" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/f20ce3e0-c3c6-4b8c-b1f2-05f1578cf9fe">|<img width="536" alt="스크린샷 2023-08-09 오후 10 58 40" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/996cd90d-ed48-4604-b130-e0080927cd2b">|

2023-08-09 14:13 UTC, Jooeun-K commented on components/common/Modal/index.tsx
> +  width: 80%;
```suggestion
  width: calc(100% - 24px);
```
이렇게 규격을 잡는건 어떨까요?
지금은 모바일 규격에서 봤을 때 피그마의 디자인과 상이하게 느껴지네요! (여백이 너무 커서)
<img width="343" alt="스크린샷 2023-08-09 오후 11 10 08" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/cf3f2678-203e-4516-95f5-5b56827c466b">

but.. 어차피 허니비의 UI/UX 개선 버전에 맞추어 수정 작업을 한 번 싹 진행해야 할 것 같아서, 이건 지금은 일단 미뤄두고 UI 수정 작업 진행할 때 같이 고쳐도 될 것 같습니다~
이 코멘트의 적용 여부는 담의 선택에 맡길게요

2023-08-12 16:13 UTC, yunwoo-yu reviewed
고생하셨어요 담 오탈자 수정 하면 승인 빠르게 눌러드리겠습니다~!!

2023-08-12 16:13 UTC, yunwoo-yu commented on components/Card.tsx
>  import CardPlayButton from './button/CardPlayButton'
```suggestion
import CardPlayButton from './Button/CardPlayButton'
```
- 폴더명이 `button` 이네용!? 아마 컨벤션이 파스칼케이스라 대문자로 되어있을텐데 변경해주시면 감사합니다 👍
- 아마 전체적으로 저희 얘기했던걸로 변경될거라 나중에 한번에 하셔도 문제는 없을거 같습니다ㅎㅎ

2023-08-12 16:13 UTC, yunwoo-yu commented on components/memory-list/MemoryDetail.tsx
> +  justify-contents: space-around;
```suggestion
  justify-content: space-around;
```
- 오탈자 하나 찾아냈습니다 👍

2023-08-12 16:26 UTC, j2h30728 commented on components/memory-list/MemoryDetail.tsx
> +  justify-contents: space-around;
매의 눈 갓론...감사합니다!

2023-08-12 16:38 UTC, yunwoo-yu approved these changes

2023-08-12 16:39 UTC, Jooeun-K approved these changes
수정 된 것 확인했습니다~!! 정말 장기간 작업한 PR인데 고생 많았어요 담ㅎㅎㅎ
|아이폰|안드|
|---|---|
|![스크린샷 2023-08-13 오전 1 35 14](https://github.com/miind-palace/mind-palace-FE/assets/90050960/1e2aa44a-f4b5-42aa-a685-045a03bd1915)|![스크린샷 2023-08-13 오전 1 35 22](https://github.com/miind-palace/mind-palace-FE/assets/90050960/339c4b79-1c08-4436-853f-843cbde981b2)|

2023-08-12 16:41 UTC, merged