Feature #71
miind-palace/mind-palace-FE pull request #74
Opened 2023-08-06 08:56 UTC by yunwoo-yu

## 관련 문서

Closes #71 

## 변경사항:

- 작은 단위에 사용할 로더 한개 더 추가했습니다. (사용 용도가 아직 명확하지 않아 portal은 걸지않았습니다.)
- 기존 CubeLoader 컴포넌트 동적 props 값들 추가했고 폴더 구조 변경해두었습니다!
- CubeLoader backdrop 사용시 isBackColor 속성 추가하시면 됩니다! 기본값 rgba(0,0,0,0.2) 변경 시 backColor=string 으로 사용

## 확인할 목록:

- 로컬에서 로더가 필요한 부분 적용

2023-08-07 00:13 UTC, hyeonheebee commented
로더 작업 감사합니다 ! 👍 미니 로더는 감사히 잘 쓰겠습니다 +_+

2023-08-09 03:48 UTC, Owonie requested changes
FlippingLoader가 로딩 스피너로 사용된다면 z-index을 화면 최상단으로 올리는게 더 좋을 것 같습니다, style 확인만 부탁드려요~

2023-08-09 03:48 UTC, Owonie commented on components/common/Loader/FlippingLoader.style.ts
작은 로더는 스켈레톤 컴포넌트로서 작동하는 건가요? 
![image](https://github.com/miind-palace/mind-palace-FE/assets/70142275/a7722cc2-8fa4-4979-bd50-85e6b1c42de1)
로컬환경에서 돌려보니, 페이지 밑으로 표시되고 있는데, 큰 로더와는 달라서 여쭤봅니다~

2023-08-09 04:32 UTC, hyeonheebee commented on components/common/Loader/FlippingLoader.style.ts
작은로더의 위치는 랜덤박스 위를 생각하고 있어서 z-index 올려주시면 감사하겠습니다( :) )

2023-08-09 14:27 UTC, Jooeun-K reviewed
질문 & 제안이 있어 코멘트 남겨두었으니 확인 부탁드려용

2023-08-09 14:27 UTC, Jooeun-K commented on components/common/Loader/CubeLoader.tsx
> +  isBackColor?: boolean
isBackColor는 Background Color를 가지고 있는지의 여부를 나타내는 boolean 데이터인가요?
그게 맞다면, 신경쓰이는 지점이 두 가지 있습니다!

1. isBackColor라는 이름이 모호하게 느껴져요. 해당 컴포넌트가 backColor를 가지고 있는지의 여부를 나타낸다면 hasBackColor쪽이 더 적절하지 않을까요?
2. backColor prop이 어차피 optional인데, isBackColor를 따로 둘 필요가 있을까요? backColor 값의 유무를 가지고 CubeLoader 컴포넌트 내부에서 변수 선언해도 되지 않을까 싶어요
```
// 이런 식으로
const hasBackColor = !!backColor
```

2023-08-09 15:00 UTC, yunwoo-yu commented on components/common/Loader/FlippingLoader.style.ts
- 확인했습니다👍

2023-08-10 10:12 UTC, Owonie approved these changes
로더 스타일 수정 확인했습니다, 수고하셨습니다!

2023-08-10 12:15 UTC, Jooeun-K commented on components/common/Loader/CubeLoader.tsx
> +}: CubeLoaderProps) => {
🤔🤔🤔🤔 이거 고민되네용..
만약 그런 의도가 있다면 존재해도 될 것 같긴 합니다. 제가 헷갈린 이유가 변수명 때문에 backColor의 존재 여부만을 가리는 prop이라고 생각했기 때문인 것 같아요.

다만 그렇게되면 해당 변수가 나타내는 것이 `backColor 값의 존재 여부` 와는 별개로 해당 값을 화면에 나타낼지 안 나타낼지를 가리게 되는거니까 showBackColor가 나을 것 같아요.
`hasBackColor` vs `showBackColor`

이건 좀 취향에 따라 좌우되는 부분이라 조심스럽네용
일단 제 제안은 이렇고, 결정은 아론에게 맡기겠습니다!

2023-08-10 12:46 UTC, yunwoo-yu commented on components/common/Loader/CubeLoader.tsx
> +}: CubeLoaderProps) => {
- 제안 감사합니다 👍 사실 검정 배경말고는 쓸일이 있을까 싶기도 해서 showBackColor 로 변경하고 true면 화면에 나타내는 형태로 일단 사용해 보겠습니다!!🙇‍♂️

2023-08-12 12:47 UTC, Jooeun-K approved these changes
변경사항 확인했습니다 👍

2023-08-12 16:37 UTC, j2h30728 approved these changes
로컬에 받아서 제가 사용할 부분에 직접 적용해보니 정말 깔끔하더라구요! 
고생했어요. 아론!!

2023-08-12 16:41 UTC, brother1-4752 submitted a review, later dismissed
로더 퀄리티 짱이에요! 수고많으셨습니다!!

2023-08-12 17:23 UTC, yunwoo-yu commented
@Jooeun-K @brother1-4752 @j2h30728 
- 로더 경로가 변경되는 바람에 크흠,, 시간나실 때 승인 부탁드립니다!!

2023-08-12 17:26 UTC, j2h30728 approved these changes

2023-08-12 17:30 UTC, brother1-4752 approved these changes

2023-08-12 17:35 UTC, merged