Feature #79 메인페이지 로딩 상태 처리한다
miind-palace/mind-palace-FE pull request #81
Opened 2023-08-15 17:36 UTC by brother1-4752

## 관련 문서
#79

## 변경사항:
- Suspense와 fallback를 사용해 비동기적으로 로딩 상태를 처리하였습니다.
- 로딩시, CubeLoader가 보이도록 했습니다.
- Suspense만 사용시, CubeLoader가 거의 보이지 않았습니다. 그래서 의도적으로 5.5초 동안은 CubeLoader가 보이도록 CustomSuspense컴포넌트를 만들어 적용했습니다.

## 확인할 목록:
- 코드 레벨 확인

2023-08-16 08:27 UTC, Owonie commented on pages/main/index.tsx
> +
여기 공백칸은 삭제해도 좋을 것 같습니다!

2023-08-16 08:31 UTC, Owonie requested changes
styled 부분에 공백 칸만 확인해주시면 될 것 같습니다!

2023-08-16 08:31 UTC, Owonie commented on components/common/Suspense/CustomSuspense.tsx
커스텀 서스펜스를 구현해서 로더를 추가하는 작업이군요, 깔끔한 코드 잘봤습니다!

2023-08-17 09:41 UTC, Jooeun-K reviewed
코멘트 몇가지 있어서 달아두었습니다! 확인 부탁드려욘 👍

2023-08-17 09:41 UTC, Jooeun-K commented on components/common/Suspense/CustomSuspense.tsx
> +  const [loadingDone, setLoadingDone] = useState(false)
상태명때문에 해당 상태 타입이 boolean임을 유추하기 힘든 것 같아요!
isLoadingDone이 낫지 않을까 싶지만, 이건 개인 취향에 따른 부분이라 반드시 적용하지는 않으셔도 괜찮습니다~
```suggestion
  const [isLoadingDone, setIsLoadingDone] = useState(false)
```

2023-08-17 09:41 UTC, Jooeun-K commented on lib/types/mainTypes.ts
> +export interface CustomSuspenseProps {
내부에 구현된 타입 모듈이 type이 아닌 interface인데 파일명이 `mainTypes.ts`인 이유가 있을까요~?

2023-08-17 09:41 UTC, Jooeun-K commented on lib/types/mainTypes.ts
> +}
그리고 이정도 규모의 타입이면 굳이 types 폴더에 분리하지 않고 CustomSuspense 컴포넌트 내에 작성하고 export만 해도 괜찮지 않을까.. 싶은데 다른 분들은 어떻게 생각하는지 궁금하네요🤔
요것도 그냥 의견이 궁금해서 달아두는거라 반드시 적용하여 수정하지는 않으셔도 괜찮습니다

2023-08-17 10:35 UTC, Owonie approved these changes

2023-08-17 10:36 UTC, Owonie approved these changes

2023-08-17 11:05 UTC, brother1-4752 commented on components/common/Suspense/CustomSuspense.tsx
감사합니다! 공백 제거해서 리리퀘 보내겠슴돠!

2023-08-17 11:06 UTC, brother1-4752 commented on components/common/Suspense/CustomSuspense.tsx
> +  const [loadingDone, setLoadingDone] = useState(false)
is붙이는게 더 명확하겠네요! 수정하겠슴돠

2023-08-17 11:45 UTC, Owonie approved these changes
수정 확인했습니다!

2023-08-17 11:55 UTC, Jooeun-K approved these changes

2023-08-17 12:03 UTC, merged