Feature #83
miind-palace/mind-palace-FE pull request #86
Opened 2023-08-19 15:16 UTC by brother1-4752

## 관련 문서
Closes #83 

## 변경사항:
- 3D 모델 세부 노드에 마우스 이벤트 적용했습니다. 클릭 이벤트 적용한 세부 노드는 책더미, 노란책, 파란책, 책장, 잎파리입니다.
- 각 노드에 hover시 기본적으로 색상 그라데이션되도록 적용했습니다.
https://github.com/miind-palace/mind-palace-FE/assets/60454376/5a53e38b-e89d-4729-abb4-fc3ecb43f0b9

- 책 노드 클릭시, /memory-list이동 후 랜덤으로 카드 컴포넌트 띄우도록 하였습니다. 책장 클릭시, /memory-list으로 라우팅됩니다.
https://github.com/miind-palace/mind-palace-FE/assets/60454376/a7269fd9-7b87-400d-bd17-d8cf2fccc6e7

- lib/types폴더 삭제하고, 루트에서 types 디렉토리 관리하기로 통일한거 반영하였습니다.(관련커밋 : https://github.com/miind-palace/mind-palace-FE/commit/5cdd27b4d0e39a73d40708a43f8bc8da64d68846)

## 확인할 목록:
- 코드 레벨 확인

2023-08-25 13:44 UTC, j2h30728 reviewed
올려주신 영상도 잘봤습니다! 정말 멋지게 구현해주셨더라구요. 고생하셨어요!

혹시 메인 화면에서 클릭할 수 있는 요소에 호버 했을때 커서를 포인터로 변경하는 방식은 어떻게 생각하시나요?

2023-08-25 14:44 UTC, Owonie reviewed
코드 구현하느라 수고많으셨습니다. 코드리뷰 확인해주시면 다시 답장 드리겠습니다!

2023-08-25 14:44 UTC, Owonie commented on components/main/MainRoom.tsx
> +  const [bookshelfHovered, setBookshelfHovered] = useState(false)
useState를 이용해서 hover의 여부를 저장하고, useFrame 내부에서 조건부로 오브젝트의 속성을 변경하는 코드 잘봤습니다. MainRoom의 렌더링 방식이 리액트의 리렌더링 방식과는 다르다고 생각이 드는데, 혹시 해당 오브젝트(책장, 책, 잎사귀 등)를 비제어 컴포넌트 형식으로 구현하면 어떨까 하는 생각이 있어요!
useState 여러개와 useFrame을 사용해서 상태체크를 하는 것 보단 성능 상 훨씬 좋지 않을까 싶습니다!

2023-08-25 19:24 UTC, brother1-4752 commented on components/main/MainRoom.tsx
> +        onPointerOut={(e) => setBookshelfHovered(false)}
@Owonie 
비제어 형식 공부하면서 궁금한 점이 생겼습니다.

제어 형식(useState) : 유저의 액션마다 리렌더링 발생, 유의미하지 않은 사용자의 행동까지 모두 반영하여 리소스 낭비 또는 성능 저하를 일으킬 수 있다.
비제어 형식(useRef) : 제출이나 클릭과 같은 최종적인 상황에서만 값에 접근하여 리렌더링을 방지할 수 있다. 그러나 '유저 행동의 최신 값'에 접근하기 힘들다.

현재 책장과 화분, 그리고 책더미 노드는 '00hovered'라는 state의 실시간 최신값을 반영하여 색상 효과를 적용하고 있습니다. 기존 방식은 useState를 사용하여 최신값 접근에 가능했습니다. 만약 useRef로 변경하면 유저의 행동(마우스 over | out) 최신값에 접근이 어려워, 색상 효과를 적용하기 힘들겠다는 생각이 들더라고요.

혹시 제가 잘못 이해한 부분이 있다면, 말씀 부탁드리겠습니다. 관련 내용 아래 첨부할게요!!

![image](https://github.com/miind-palace/mind-palace-FE/assets/60454376/c533e406-bd63-4533-abdd-805caefb895e)

2023-08-26 05:27 UTC, Owonie commented on components/main/MainRoom.tsx
> +        onPointerOut={(e) => setBookshelfHovered(false)}
리액트의 웹 컴포넌트를 구현할 때는 네모가 말한 것 처럼, 실시간으로 반영되어야 하는 내용을 useState로 필요한 값을(ex: bookshelfHovered) 제공할 필요가 있습니다. 메인페이지를 구현하면서, 제가 들었던 생각은 "과연 MainRoom이라는 3d 모델 컴포넌트가 리액트스럽게 동작하고 있는가?"였습니다. 

```React.js
 let bookHovered = false

 useFrame(() => {
    //책장
    if (bookshelfRef.current !== undefined) {
      bookshelfRef.current.position.z = bookHovered
        ? THREE.MathUtils.lerp(bookshelfRef.current.position.z, -1, 0.025)
        : THREE.MathUtils.lerp(bookshelfRef.current.position.z, -1.03, 0.025)

      materials['Material.007'].color.lerp(
        bookHovered ? new THREE.Color(Math.floor(Math.random() * 16777216)) : new THREE.Color('#D69034'),
        0.01
      )
    }
}

  <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Material.007']}
        position={[1.404, 3.387, -1.132]}
        ref={bookshelfRef}
        scale={0.645}
        onPointerOver={(e) => (e.stopPropagation(), (bookHovered = true))}
        onPointerOut={(e) => (bookHovered = false)}
        onClick={() => router.push('/memory-list')}
      />

```
위의 코드는 제가 임의로 살짝 수정한 버전입니다. state가 아닌 let으로 hovered 값을 사용해봤는데, 기존 기능이 정상 동작하는 것을 확인했습니다. MainRoom이 리액트의 리렌더링 통제에서 벗어나, three.js에서 제공하는 3d 렌더링 엔진 위에서 동작한다는 것으로 추측합니다.  let으로도 충분히 오브젝트를 컨트롤 할 수 있다면 useState를 이용해 부가적인 리렌더링을 일으키지 않아도 된다고 생각해요. 

비제어 컴포넌트를 언급한건, state를 이용해 컴포넌트를 관리하지 않아도 된다고 말씀드리기 위해서 입니다. stateless 컴포넌트가 좀 더 적절한 표현이 될 것 같네요!

2023-08-26 08:07 UTC, brother1-4752 commented on components/main/MainRoom.tsx
> +        onPointerOut={(e) => setBookshelfHovered(false)}
와우.. 상세한 설명 감사합니다! useState / useRef만 생각했는데, let으로 hovered값을 충분히 컨트롤 가능하군요!! let으로 반영하겠슴돠👍

2023-08-26 11:13 UTC, hyeonheebee commented
구현하느라 고생하셨습니다!! 그라데이션 효과도 가능하게 신경써주셔서 감사해요 :) 제가 좀 더 디테일한 메인룸 추가 디자인 설명을 드렸어야하는데 그렇지 못했는데도 넣을 수 있는 효과들을 많이 신경써주셔서 감사합니다! 좀있다 뵙겠습니다 :)

2023-09-08 11:49 UTC, j2h30728 commented
마지막 커밋을 보니 Main 폴더는 아직 컨벤션 적용 전인가요?
혹시 `git config core.ignorecase` 이 명령어를 실행하고 깃 캐시내용을 지우고 커밋을 해도 동일하게 적용되고 있는지 궁금해요!

hover 수정하신부분 확인했습니다. 정말 고생하셨어요~!!

추후에 디자인 추가가 일어난다면, hover와 함께 테두리를 달리하거나 색상을 다르게 표시해서 어떤 것이 hover 되었는지 확인시켜주는 것도 좋을것 같아요. 웹에서 확인해보니 너무 이뻐서 깜짝 놀랬어요!

2023-09-08 12:18 UTC, Owonie approved these changes
컨벤션 수정과 storedDummyMemory 로 랜덤 유저카드 데이터 fetch하는 부분 잘 봤습니다, 수고하셨습니다!

2023-09-08 12:25 UTC, Jooeun-K requested changes
고생하셨습니다!!
<img width="649" alt="스크린샷 2023-09-08 오후 9 18 34" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/74dcbdf3-7c2c-49ba-ac80-cf1aec6eef05">

그런데 디스코드 discussion에도 올렸지만 저는 main에서 클릭 이벤트를 통해 memory-list로 진입하면 자꾸 이런 에러가 뜨네요..🥲 서버사이드프롭스 내에서 서버 요청이 실패해서 발생하는 에러인 것 같은데, 확인 함만 부탁드리겠습니다!

혹시나 싶어서 env도 최신화 한 다음에 테스트하고, 캐시도 날린 다음에 해봤는데 안되네욘..
<img width="1624" alt="스크린샷 2023-09-08 오후 9 00 06" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/3fbc5d0f-b42a-4ddf-aa76-b2e17151b768">

2023-09-08 12:25 UTC, Jooeun-K commented on lib/constant/dummyMemoryList.ts
요 파일은 테스트를 위해 생성한 파일이죠??
만약 개발 마무리한 지금 시점에 필요없다면 삭제해주셔도 괜찮을 것 같아요~

2023-09-08 16:21 UTC, Owonie approved these changes
로컬환경에서 정상작동하는 것을 확인했습니다. 백엔드 이슈 해결했으니 확인해보신 후 merge하시면 될 것 같아요!

2023-09-19 02:35 UTC, brother1-4752 reviewed
확인 감사합니다👍

2023-09-22 11:15 UTC, Owonie approved these changes
컨벤션 확인 작업하시느라 수고많으셨습니다!

2023-09-22 11:15 UTC, Owonie commented on lib/types/mainTypes.ts
타입을 컴포넌트 내부로 정리하셨군요, 훨씬 폴더정리가 깔끔하게 된 것 같아요!

2023-09-22 13:08 UTC, yunwoo-yu approved these changes
LGTM 👍

2023-09-24 14:32 UTC, brother1-4752 reviewed
확인

2023-09-24 14:33 UTC, merged