Feature #75 업로드 페이지 디자인 변경과 컴포넌트를 분리한다.
miind-palace/mind-palace-FE pull request #89
Opened 2023-10-09 14:30 UTC by yunwoo-yu

## 관련 문서

Closes #75 

## 변경사항:

- 업로드 페이지 디자인 변경본 작업
- kakao kalro v2 업데이트
- 기능 별 컴포넌트 분리
- 유튜브 기능 버튼 아이콘 변경 작업
- 이미지 생성 시 로더 적용

## 확인할 목록:

- 로컬에서 테스트 해보시면 좋을 거 같습니다!
- info 기능은 추후에 탭바 컴포넌트 작업이 완료되면 진행하겠습니다!
- POST 기능은 인증쪽 백엔드 로직 완료되면 상의 후 변경이 필요해 보입니다

2023-10-14 01:27 UTC, j2h30728 commented on components/Upload/UploadYouTubePlayer/UploadYouTubePlayer.tsx
> +        <YouTubePlayerButton videoId={makeYouTubeVideoId(youtubeUrl) || ''} isAutoPlay={false} color="#171717" />
처음 youtubuUrl을 입력한 뒤에 다른 Url 로 교체할 경우에는 새로운 url로 인식하지 못하는 것. ㅏㅌ아요!
key={youtueUrl} 을 주어 새로 컴포넌트를 마운트 시키는건 어떨까요?

2023-10-14 01:31 UTC, j2h30728 commented on components/Upload/UploadTextarea/UploadTextarea.style.ts
> +export const CustomTextarea = styled(ReactTextareaAutosize)`
오 ReactTextareaAutosize 이거 처음 보는거에요.
텍스트가 많아 지면 칸에 맞게 라인 수는 늘어나지만 방향키 말고는 라인간의 안되더라구요.
혹시 이런것도 이 친구 담당인가요?

2023-10-14 08:49 UTC, yunwoo-yu commented on components/Upload/UploadTextarea/UploadTextarea.style.ts
> +export const CustomTextarea = styled(ReactTextareaAutosize)`
- 아 제가 `overflow: hidden` 을 걸어놔서 스크롤이 안먹었네요!! auto 로 변경해두겠습니다 👍

2023-10-14 08:49 UTC, yunwoo-yu commented on components/Upload/UploadYouTubePlayer/UploadYouTubePlayer.tsx
> +        <YouTubePlayerButton videoId={makeYouTubeVideoId(youtubeUrl) || ''} isAutoPlay={false} color="#171717" />
- 오 재생 중에 변경시에 그런현상이 있었네요!!
- key를 변경하는 방식으로 하니 state도 딱 바뀌고 좋은데요? 감사합니다 👍

2023-10-14 10:03 UTC, Jooeun-K requested changes
고생하셨읍니다 👍👍👍
그런데 요 키워드 입력 Input 텍스트가 너무 작더라고요!
피그마 확인하고 피그마 규격이랑 맞춰야 될 것 같아요.
폰트 규격 한 번 체크해주시고, 궁금한게 있어서 코멘트 조금 달아놨으니 고것도 가볍게 확인 부탁드립니다~
<img width="363" alt="스크린샷 2023-10-14 오후 5 41 04" src="https://github.com/miind-palace/mind-palace-FE/assets/90050960/1444aaac-1849-484f-b877-2eae07bfcb16">

2023-10-14 18:57 UTC, yunwoo-yu commented on hooks/useChangePreviewImage.ts
> +          return alert('이미지는 너비 568px 이상 높이 264이상의 이미지로 넣어주세요.')
- 크으 디테일 감사합니다!

2023-10-14 18:57 UTC, yunwoo-yu commented on components/common/Button/LargeButton.tsx
> +}
- 업로드 페이지 뿐만 아니라 로그인 회원가입 쪽에서도 사용한다고 들었기도 했고 나~중에 기능이 더 추가 됐을 때 해당 버튼이 사용될 가능성도 있다고 생각되어서 크기로 추상화해서 이름을 지었습니다!! (현재는 가장 큰 버튼같아서요ㅎㅎ)
- 생각해두신 더 좋은 컴포넌트 명이 있을까요!!

2023-10-14 18:57 UTC, yunwoo-yu commented on pages/api/suggestion-image.ts
> +          'poorly drawn hands, poorly drawn feet, photorealistic, poorly drawn face, out of frame, body out of frame, watermark, distorted face, bad anatomy, ugly, mutilated, disfigured, mutation, ba
- 맞습니다 테스트 거쳐가면서 문제 있는것들 추가로 계속 넣어주면 활용도 높을 거 같아요 👍

2023-10-14 18:57 UTC, yunwoo-yu commented on pages/upload/index.tsx
> +        <PreviewLabel previewImageUrl={previewImageUrl} onChangeBackgroundImage={onChangeBackgroundImage} />
- 요거는 제가 기존 `PreviewLabel` 컴포넌트에 `input` 요소를 추가해서 분리해놓고 이름을 변경을 못했네요 😅
- 변경하겠습니다!! 현재 생각나는 이름은 `UploadImageField`로 간단하게 넣을까 싶습니다 (추천해주셔도 좋구요👀)

2023-10-20 12:21 UTC, Jooeun-K commented on components/common/Button/LargeButton.tsx
> +}
Large가 있으면 Medium, Small Button도 있어야 할 것 같은데 현재 우리 명세에는 그런 버튼은 따로 없지 않나 싶어서 궁금해 물어본거였어요~! 만약 대응하는 개념의 버튼이 없다면 그냥 'Button' 으로 하는게 낫지 않을까 하는 개인적인 의견이 잇습니다 🤔 
(물론 이 코멘트 반영은 아론의 자유지만.. 다른 사람들 의견도 한 번 받아보는것도 좋을 것 같아요. 공통 컴포넌트 이름은 한 번 정하면 나중에 바꾸는데 비용이 많이 들어가니까여)

2023-10-20 12:22 UTC, Jooeun-K commented on pages/upload/index.tsx
> +        <PreviewLabel previewImageUrl={previewImageUrl} onChangeBackgroundImage={onChangeBackgroundImage} />
그정도면 괜찮은 것 같아요!!!!!!!!!!! 따봉입니다 👍

2023-10-20 12:26 UTC, Jooeun-K approved these changes
고생하셨습니다 👍👍👍
디자인상 이슈는 해결되어서 승인드려요!

2023-10-22 07:48 UTC, yunwoo-yu commented on components/common/Button/LargeButton.tsx
> +}
- 오호.. 하긴 Large만 있으면 이상하긴 하네요 그런식으로의 접근은 생각도 못했읍니다.. 모두의 의견을 받기엔 병목이 좀 있을거 같아 일단 Button 으로 변경해두도록 하겠습니다 👍

2023-10-22 07:52 UTC, j2h30728 commented
정말 고생많았어요! 역시 갓아론~!

2023-10-22 07:53 UTC, j2h30728 approved these changes

2023-10-27 02:21 UTC, j2h30728 approved these changes

2023-10-27 16:21 UTC, Owonie approved these changes
많은 기능을 구현하시느라 수고 많으셨습니다 :)

2023-10-27 16:21 UTC, Owonie commented on hooks/useCreateSuggestionImage.ts
handler 명을 훨씬 명시적으로 변경해 가독성이 훨씬 좋아요 :)

2023-10-27 16:21 UTC, Owonie commented on components/Upload/KeywordInput/KeywordInput.tsx
> +const KeywordInput = ({ hasError, onClickButton, ...props }: SearchInputProps, ref: Ref<HTMLInputElement>) => {
혹시 이 부분만 컴포넌트의 props type 명을 KeywordInputProps 가 아닌 SearchInputProps로 지정해준 이유가 있나요?

2023-10-28 11:11 UTC, yunwoo-yu commented on components/Upload/KeywordInput/KeywordInput.tsx
> +const KeywordInput = ({ hasError, onClickButton, ...props }: SearchInputProps, ref: Ref<HTMLInputElement>) => {
- 이런 이것도 리팩하면서 뺴먹었네요ㅎㅎ,, 일단 다시 승인을 받기 힘들것 같아 기억해두고 추후 다른 작업 시 끼워서 작업하겠습니다 매의눈 감사해요 👍

2023-10-28 11:12 UTC, merged