Feature #67 로그인/회원가입 통신 로직 개선 및 버그 해결
miind-palace/mind-palace-FE pull request #90
Opened 2023-10-14 12:53 UTC by Jooeun-K

## 관련 문서

Closes #67 #68 

## 변경사항:

- axios 공통 설정 core 유틸로 병합 bdf1126d44c03963b3b8f8ff9455291b25e30821
- 회원가입 페이지 이메일 중복 건증 과정 추가
- 로그인/회원가입 정상 동작하도록 로직 개선
- 테스트를 위한 임시 로그아웃 버튼 추가 c76a1a3fb38b82a9906cef0da357fcba6ef81584

## 확인할 목록:

- 프리뷰 혹은 로컬에서 기능 정상 동작 여부 확인

2023-10-14 20:05 UTC, yunwoo-yu requested changes
- 코드 잘 봤습니다!! 별건아니고 `SignInForm` 컴포넌트에서 함수명 체인지 하나 안된거 같아서 그것만 코멘트 남겨놨어요 🙇‍♂️

2023-10-20 12:17 UTC, Jooeun-K commented
@yunwoo-yu 핸들러 이름 수정했습니다~!
작업하며 주석 해제 안한 부분도 발견해서 같이 수정했어요~ [43c8b4a](https://github.com/miind-palace/mind-palace-FE/pull/90/commits/43c8b4a84a66979c92ebfb412d1c358dd6c8d6ee)

2023-10-20 12:18 UTC, yunwoo-yu submitted a review, later dismissed

2023-11-03 10:07 UTC, Owonie requested changes
수고 많으셨습니다! 변수명 수정만 체크해주시면 될 것 같아요 :)

2023-11-03 10:07 UTC, Owonie commented on pages/sign-up/index.tsx
> +export const SING_UP_STEP = {
SIGN_UP_STEP 으로 수정해주시면 좋을 것 같습니다 😊

2023-11-03 10:17 UTC, Jooeun-K commented
리뷰 반영하였습니다~! @Owonie
커밋이 추가되어 승인이 초기화되어 다시 한 번 확인 부탁드릴게요! @yunwoo-yu

2023-11-03 10:22 UTC, yunwoo-yu submitted a review, later dismissed

2023-11-03 10:51 UTC, Owonie requested changes

2023-11-03 10:51 UTC, Owonie commented on components/CheckEmailForm/CheckEmailForm.tsx
> +      alert(msg)
현재 msg 내부에는 duplicated 속성이 포함되어있습니다. msg를 그대로 alert로 출력하면 유저가 이메일 체크의 결과 값을 읽지 못하기에, 수정이 필요해보이네요 :)
![image](https://github.com/miind-palace/mind-palace-FE/assets/70142275/18cb3c62-f899-4a8d-b000-a60f8e1ad183)

2023-11-03 11:33 UTC, Jooeun-K commented on components/CheckEmailForm/CheckEmailForm.tsx
> +      alert(msg)
요 부분 해결했습니다 확인 부탁드려요~! [fix: api 스펙 변경으로 인한 버그 수정](https://github.com/miind-palace/mind-palace-FE/pull/90/commits/fe63f859f4e4fe79e74088010b0cf5f2a514b029)
![스크린샷 2023-11-03 오후 8 31 38](https://github.com/miind-palace/mind-palace-FE/assets/90050960/4aba7a0e-50c6-4db7-9bad-5f194f83ffba)

2023-11-03 11:33 UTC, Jooeun-K commented on components/CheckEmailForm/CheckEmailForm.tsx
> +      alert(msg)
@Owonie

2023-11-04 04:36 UTC, Owonie approved these changes
확인했습니다, 빠른 수정 감사합니다!  :)

2023-11-04 05:33 UTC, j2h30728 commented on components/SigninForm/SigninForm.tsx
> +  const handleChangeSigninValue = (e: ChangeEvent<HTMLInputElement>) => {
헤헤..별거는 아니지만 signin 과 signup 에서 i와 u가 기본적으로 대문자지만 몇개만 소문자 인것같아요.
현재 SignupForm 과 SigninForm 컴포넌트 이름도 소문자로 되어있어요.
역시 곰곰 깔끔한 코드 잘봤어요!!! 고생하셨어요!

2024-03-02 01:27 UTC, yunwoo-yu approved these changes

2024-03-02 01:29 UTC, brother1-4752 approved these changes

2024-03-02 04:52 UTC, j2h30728 approved these changes

2024-03-02 04:53 UTC, Jooeun-K commented
@j2h30728 
담 리뷰는 별도 PR로 반영하겠습니다~! 어푸 감사해욤!

2024-03-02 04:56 UTC, merged